/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package erp;

/**
 *
 * @author Heet Lakhani
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
public class FacultyPostNotice extends javax.swing.JFrame {
     Connection con;
    PreparedStatement pst;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FacultyPostNotice.class.getName());

    /**
     * Creates new form FacultyPostNotice
     */
    public FacultyPostNotice() {
        initComponents();
        setLocationRelativeTo(null);
        populateGradeDropdown();
        populateDivisionDropdown();
        
        // Add character counters
        addCharacterCounters();
    }
private void populateGradeDropdown() {
        cmbGrade.removeAllItems();
        cmbGrade.addItem("--Select Grade--");
        cmbGrade.addItem("All");
        for (int i = 1; i <= 10; i++) {
            cmbGrade.addItem(String.valueOf(i));
        }
    }
    
    private void populateDivisionDropdown() {
        cmbDivision.removeAllItems();
        cmbDivision.addItem("--Select Division--");
        cmbDivision.addItem("All");
        cmbDivision.addItem("A");
        cmbDivision.addItem("B");
        cmbDivision.addItem("C");
        cmbDivision.addItem("D");
    }
    private void addCharacterCounters() {
        // Title character counter (max 100)
        txtNoticeTitle.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateTitleCounter();
            }
            
            @Override
            public void removeUpdate(DocumentEvent e) {
                updateTitleCounter();
            }
            
            @Override
            public void changedUpdate(DocumentEvent e) {
                updateTitleCounter();
            }
            
            private void updateTitleCounter() {
                int length = txtNoticeTitle.getText().length();
                lblTitleCounter.setText(length + "/100 characters");
                
                if (length > 100) {
                    lblTitleCounter.setForeground(java.awt.Color.RED);
                } else {
                    lblTitleCounter.setForeground(java.awt.Color.BLACK);
                }
            }
        });
        
        // Description character counter (max 500)
        lblDescriptionCounter.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateDescriptionCounter();
            }
            
            @Override
            public void removeUpdate(DocumentEvent e) {
                updateDescriptionCounter();
            }
            
            @Override
            public void changedUpdate(DocumentEvent e) {
                updateDescriptionCounter();
            }
            
            private void updateDescriptionCounter() {
                int length = lblDescriptionCounter.getText().length();
                lblCounter.setText(length + "/500 characters");
                
                if (length > 500) {
                    lblCounter.setForeground(java.awt.Color.RED);
                } else {
                    lblCounter.setForeground(java.awt.Color.BLACK);
                }
            }
        });
        
        // Initialize counters
        lblTitleCounter.setText("0/100 characters");
        lblCounter.setText("0/500 characters");
    }
    private void clearForm() {
        txtTitle.setText("");
        lblDescriptionCounter.setText("");
        cmbGrade.setSelectedIndex(0); // "--Select Grade--"
        cmbDivision.setSelectedIndex(0); // "--Select Division--"
        txtTitle.requestFocus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        panelForm = new javax.swing.JPanel();
        txtTitle = new javax.swing.JLabel();
        lblInfoBox = new javax.swing.JLabel();
        lblNoticeTitle = new javax.swing.JLabel();
        txtNoticeTitle = new javax.swing.JTextField();
        lblTitleCounter = new javax.swing.JLabel();
        lblNoticeDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblDescriptionCounter = new javax.swing.JTextArea();
        lblCounter = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbGrade = new javax.swing.JComboBox<>();
        lblDivision = new javax.swing.JLabel();
        cmbDivision = new javax.swing.JComboBox<>();
        btnPostNotice = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setBackground(new java.awt.Color(0, 0, 102));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Post Notice");
        headerPanel.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btnBack.setBackground(new java.awt.Color(255, 0, 0));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("<-- Back To Dashboard");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        headerPanel.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, -1, -1));

        getContentPane().add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 80));

        contentPanel.setBackground(new java.awt.Color(204, 204, 204));
        contentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelForm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitle.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        txtTitle.setText("Create New Notice: ");
        panelForm.add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 190, -1));

        lblInfoBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblInfoBox.setForeground(new java.awt.Color(204, 0, 204));
        lblInfoBox.setText("Info: Post notices for specific grades/divisions or for all students. Leave Grade and Division as \"All\" to broadcast to everyone.");
        panelForm.add(lblInfoBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 65, -1, -1));

        lblNoticeTitle.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        lblNoticeTitle.setText("Notice Title: ");
        panelForm.add(lblNoticeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 125, -1, -1));

        txtNoticeTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelForm.add(txtNoticeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 155, 820, 45));

        lblTitleCounter.setText("0/100 characters");
        panelForm.add(lblTitleCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 205, -1, -1));

        lblNoticeDescription.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        lblNoticeDescription.setText("Notice Description: ");
        panelForm.add(lblNoticeDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        lblDescriptionCounter.setColumns(20);
        lblDescriptionCounter.setRows(5);
        jScrollPane1.setViewportView(lblDescriptionCounter);

        panelForm.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 820, 180));

        lblCounter.setText("0/500 characters");
        panelForm.add(lblCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        jLabel1.setText("Grade: ");
        panelForm.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        cmbGrade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Grade--", "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6", "Grade 7", "Grade 8", "Grade 9", "Grade 10" }));
        panelForm.add(cmbGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        lblDivision.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        lblDivision.setText("Division:");
        panelForm.add(lblDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, -1, -1));

        cmbDivision.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbDivision.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Division", "Division A", "Division B", "Division C", "Division D" }));
        panelForm.add(cmbDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, -1, -1));

        btnPostNotice.setBackground(new java.awt.Color(0, 204, 0));
        btnPostNotice.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnPostNotice.setForeground(new java.awt.Color(255, 255, 255));
        btnPostNotice.setText("Post Notice");
        btnPostNotice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostNoticeActionPerformed(evt);
            }
        });
        panelForm.add(btnPostNotice, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 510, 150, 45));

        btnClear.setBackground(new java.awt.Color(153, 153, 153));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear All");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        panelForm.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 150, 45));

        contentPanel.add(panelForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 900, 600));

        getContentPane().add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1200, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
FacultyDashboard fd=new FacultyDashboard();
fd.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPostNoticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostNoticeActionPerformed
String title = txtNoticeTitle.getText().trim();
        String description = lblDescriptionCounter.getText().trim();
        String grade = (String) cmbGrade.getSelectedItem();
        String division = (String) cmbDivision.getSelectedItem();
        
        // Validation
        if (title.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a notice title!", "Error", JOptionPane.ERROR_MESSAGE);
            txtTitle.requestFocus();
            return;
        }
        
        if (description.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a notice description!", "Error", JOptionPane.ERROR_MESSAGE);
            lblDescriptionCounter.requestFocus();
            return;
        }
        
        if (grade.equals("--Select Grade--")) {
            JOptionPane.showMessageDialog(this, "Please select a grade!\n\nTip: Select 'All' to send to everyone.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (division.equals("--Select Division--")) {
            JOptionPane.showMessageDialog(this, "Please select a division!\n\nTip: Select 'All' to send to all divisions.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Character limit validation
        if (title.length() > 100) {
            JOptionPane.showMessageDialog(this, "Title cannot exceed 100 characters!\nCurrent: " + title.length() + " characters", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (description.length() > 500) {
            JOptionPane.showMessageDialog(this, "Description cannot exceed 500 characters!\nCurrent: " + description.length() + " characters", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Confirmation dialog
        String targetAudience = "";
        if (grade.equals("All") && division.equals("All")) {
            targetAudience = "ALL students (all grades and divisions)";
        } else if (grade.equals("All")) {
            targetAudience = "ALL students in Division " + division;
        } else if (division.equals("All")) {
            targetAudience = "ALL students in Grade " + grade;
        } else {
            targetAudience = "Students of Grade " + grade + " Division " + division;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to post this notice?\n\n" +
            "Title: " + title + "\n" +
            "Target: " + targetAudience + "\n\n" +
            "This notice will be visible to the selected students immediately.", 
            "Confirm Post Notice", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE);
        
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        try {
            con = erp.DBConnection.connect();
            
            // Get current date
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
            String currentDate = sdf.format(new java.util.Date());
            
            // Insert notice into database
            String query = "INSERT INTO notices (title, message, date, posted_by) VALUES (?, ?, ?, ?)";
            pst = con.prepareStatement(query);
            pst.setString(1, title);
            pst.setString(2, description);
            pst.setString(3, currentDate);
            pst.setString(4, LoginSession.email); // Faculty email
            
            int result = pst.executeUpdate();
            
            pst.close();
            con.close();
            
            if (result > 0) {
                JOptionPane.showMessageDialog(this, 
                    "✅ Notice posted successfully!\n\n" +
                    "Title: " + title + "\n" +
                    "Target: " + targetAudience + "\n" +
                    "Date: " + currentDate + "\n" +
                    "Posted by: " + LoginSession.name, 
                    "Success", 
                    JOptionPane.INFORMATION_MESSAGE);
                
                // Clear form after successful post
                clearForm();
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error posting notice: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnPostNoticeActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to clear all fields?", 
            "Clear All", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE);
        
        if (confirm == JOptionPane.YES_OPTION) {
            clearForm();
            JOptionPane.showMessageDialog(this, "All fields cleared!", "Cleared", JOptionPane.INFORMATION_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FacultyPostNotice().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPostNotice;
    private javax.swing.JComboBox<String> cmbDivision;
    private javax.swing.JComboBox<String> cmbGrade;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCounter;
    private javax.swing.JTextArea lblDescriptionCounter;
    private javax.swing.JLabel lblDivision;
    private javax.swing.JLabel lblInfoBox;
    private javax.swing.JLabel lblNoticeDescription;
    private javax.swing.JLabel lblNoticeTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleCounter;
    private javax.swing.JPanel panelForm;
    private javax.swing.JTextField txtNoticeTitle;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
