/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package erp;

/**
 *
 * @author Heet Lakhani
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class FacultyDashboard extends javax.swing.JFrame {
     Connection con;
    PreparedStatement pst;
    ResultSet rs;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FacultyDashboard.class.getName());

    /**
     * Creates new form FacultyDashboard
     */
    public FacultyDashboard() {
        initComponents();
        setLocationRelativeTo(null);
        jLabel1.setText("Welcome Back Prof. " + LoginSession.name);
    lblFacultyName.setText(LoginSession.name);
     loadRecentActivity();
    }

// LOAD RECENT ACTIVITY
private void loadRecentActivity() {
    try {
        con = erp.DBConnection.connect();
        
        StringBuilder activity = new StringBuilder();
        
        // Get recent attendance records (JOIN with users table to get grade/division)
        String queryAttendance = "SELECT a.subject, a.date, u.grade, u.division FROM attendance a JOIN users u ON a.student_email = u.email WHERE a.teacher_email = ? ORDER BY a.date DESC, a.created_at DESC LIMIT 1";
        pst = con.prepareStatement(queryAttendance);
        pst.setString(1, LoginSession.email);
        rs = pst.executeQuery();
        
        if (rs.next()) {
            String relativeTime = getRelativeTime(rs.getDate("date"));
            activity.append("Attendance marked for Grade ").append(rs.getInt("grade"))
                    .append("-").append(rs.getString("division"))
                    .append(" ").append(rs.getString("subject"))
                    .append(" (").append(relativeTime).append(")\n\n");
        }
        rs.close();
        pst.close();
        
        // Get recent marks records
        String queryMarks = "SELECT m.subject, m.exam_type, u.grade, u.division, m.created_at FROM marks m JOIN users u ON m.student_email = u.email WHERE m.teacher_email = ? ORDER BY m.created_at DESC LIMIT 1";
        pst = con.prepareStatement(queryMarks);
        pst.setString(1, LoginSession.email);
        rs = pst.executeQuery();
        
        if (rs.next()) {
            String relativeTime = getRelativeTime(rs.getTimestamp("created_at"));
            activity.append("Marks entered for Grade ").append(rs.getInt("grade"))
                    .append("-").append(rs.getString("division"))
                    .append(" ").append(rs.getString("subject"))
                    .append(" ").append(rs.getString("exam_type"))
                    .append(" (").append(relativeTime).append(")\n\n");
        }
        rs.close();
        pst.close();
        
        // Get recent notices
        String queryNotices = "SELECT title, date FROM notices WHERE posted_by = ? ORDER BY date DESC LIMIT 1";
        pst = con.prepareStatement(queryNotices);
        pst.setString(1, LoginSession.email);
        rs = pst.executeQuery();
        
        if (rs.next()) {
            String relativeTime = getRelativeTime(rs.getDate("date"));
            activity.append("Notice posted: '").append(rs.getString("title"))
                    .append("' (").append(relativeTime).append(")");
        }
        rs.close();
        pst.close();
        
        con.close();
        
        // Set activity text
        if (activity.length() > 0) {
            lblRecentActivity.setText("<html>" + activity.toString().replace("\n", "<br>") + "</html>");
        } else {
            lblRecentActivity.setText("<html>No recent activity</html>");
        }
        
    } catch (Exception e) {
        lblRecentActivity.setText("<html>Error loading activity</html>");
        e.printStackTrace();
    }
}
private String getRelativeTime(java.util.Date date) {
        long diff = System.currentTimeMillis() - date.getTime();
        long days = diff / (24 * 60 * 60 * 1000);
        
        if (days == 0) {
            return "Today, " + new java.text.SimpleDateFormat("hh:mm a").format(date);
        } else if (days == 1) {
            return "Yesterday, " + new java.text.SimpleDateFormat("hh:mm a").format(date);
        } else {
            return days + " days ago";
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        lblFacultyDashboard = new javax.swing.JLabel();
        lblFacultyName = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnAttendance = new javax.swing.JButton();
        btnMarks = new javax.swing.JButton();
        btnNotices = new javax.swing.JButton();
        btnSchedule = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cardAttendance = new javax.swing.JPanel();
        markAttendance = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        cardMarks = new javax.swing.JPanel();
        enterMarks = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        cardNotice = new javax.swing.JPanel();
        postNotice = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        lblRecentActivity = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topPanel.setBackground(new java.awt.Color(0, 0, 102));
        topPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFacultyDashboard.setBackground(new java.awt.Color(255, 255, 255));
        lblFacultyDashboard.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblFacultyDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lblFacultyDashboard.setText("Faculty Dashboard");
        topPanel.add(lblFacultyDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, -1));

        lblFacultyName.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        lblFacultyName.setForeground(new java.awt.Color(255, 255, 255));
        lblFacultyName.setText("Faculty Name");
        topPanel.add(lblFacultyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, 180, -1));

        btnBack.setBackground(new java.awt.Color(255, 51, 51));
        btnBack.setText("Logout");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        topPanel.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, 110, 35));

        getContentPane().add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 80));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setBackground(new java.awt.Color(0, 0, 0));
        btnHome.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 55));

        btnAttendance.setBackground(new java.awt.Color(0, 0, 0));
        btnAttendance.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        btnAttendance.setForeground(new java.awt.Color(255, 255, 255));
        btnAttendance.setText("Attendance");
        btnAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttendanceActionPerformed(evt);
            }
        });
        jPanel1.add(btnAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, 220, 55));

        btnMarks.setBackground(new java.awt.Color(0, 0, 0));
        btnMarks.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        btnMarks.setForeground(new java.awt.Color(255, 255, 255));
        btnMarks.setText("Enter Marks");
        btnMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarksActionPerformed(evt);
            }
        });
        jPanel1.add(btnMarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 220, 55));

        btnNotices.setBackground(new java.awt.Color(0, 0, 0));
        btnNotices.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        btnNotices.setForeground(new java.awt.Color(255, 255, 255));
        btnNotices.setText("Post Notice");
        btnNotices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoticesActionPerformed(evt);
            }
        });
        jPanel1.add(btnNotices, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 215, 220, 55));

        btnSchedule.setBackground(new java.awt.Color(0, 0, 0));
        btnSchedule.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        btnSchedule.setForeground(new java.awt.Color(255, 255, 255));
        btnSchedule.setText("Manage Schedule");
        btnSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScheduleActionPerformed(evt);
            }
        });
        jPanel1.add(btnSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 220, 55));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, 620));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome Back Prof. ");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 370, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Here's what happening with your Classes Today...");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 900, 120));

        cardAttendance.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        markAttendance.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        markAttendance.setText("Mark Attendance");
        cardAttendance.add(markAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel3.setText("Take Today's Attendance");
        cardAttendance.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 140, -1));

        jPanel10.setBackground(new java.awt.Color(0, 153, 255));
        cardAttendance.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 140));

        jPanel2.add(cardAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 270, 140));

        cardMarks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterMarks.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        enterMarks.setText("Enter Marks");
        cardMarks.add(enterMarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jLabel4.setText("Add Exam Marks");
        cardMarks.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jPanel11.setBackground(new java.awt.Color(51, 204, 0));
        cardMarks.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 140));

        jPanel2.add(cardMarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 270, 140));

        cardNotice.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        postNotice.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        postNotice.setText("Post Notice");
        cardNotice.add(postNotice, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jLabel5.setText("Announce To Students");
        cardNotice.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jPanel12.setBackground(new java.awt.Color(255, 102, 0));
        cardNotice.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 140));

        jPanel2.add(cardNotice, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 270, 140));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRecentActivity.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblRecentActivity.setText("Recent Activity: ");
        jPanel9.add(lblRecentActivity, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Attendance marked for Grade 5-A English (Today, 10:30 AM)");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 860, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Marks entered for Grade 5-B Math Unit Test 2 (Yesterday, 3:45 PM)");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 860, 15));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText(" Notice posted: 'Mid-term exam schedule' (2 days ago)");
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 95, 860, 20));

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 900, 290));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 950, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttendanceActionPerformed
FacultyMarksAttendance fma = new FacultyMarksAttendance();   
    fma.setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnAttendanceActionPerformed

    private void btnMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarksActionPerformed
FacultyEnterMarks fem=new FacultyEnterMarks();
fem.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnMarksActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
FacultyDashboard fd=new FacultyDashboard();
fd.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnNoticesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoticesActionPerformed
FacultyPostNotice fpn=new FacultyPostNotice();
fpn.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnNoticesActionPerformed

    private void btnScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScheduleActionPerformed
FacultyManageSchedule fms=new FacultyManageSchedule();
fms.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnScheduleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FacultyDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttendance;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnMarks;
    private javax.swing.JButton btnNotices;
    private javax.swing.JButton btnSchedule;
    private javax.swing.JPanel cardAttendance;
    private javax.swing.JPanel cardMarks;
    private javax.swing.JPanel cardNotice;
    private javax.swing.JLabel enterMarks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblFacultyDashboard;
    private javax.swing.JLabel lblFacultyName;
    private javax.swing.JLabel lblRecentActivity;
    private javax.swing.JLabel markAttendance;
    private javax.swing.JLabel postNotice;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
