/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package erp;

/**
 *
 * @author Heet Lakhani
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
public class FacultyManageSchedule extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FacultyManageSchedule.class.getName());
Connection con;
    PreparedStatement pst;
    ResultSet rs;
    /**
     * Creates new form FacultyManageSchedule
     */
    public FacultyManageSchedule() {
        initComponents();
        setLocationRelativeTo(null);
        populateGradeDropdown();
        populateDivisionDropdown();
        populateDayDropdown();
    }
private void populateGradeDropdown() {
        cmbGrade.removeAllItems();
        cmbGrade.addItem("--Select Grade--");
        for (int i = 1; i <= 10; i++) {
            cmbGrade.addItem(String.valueOf(i));
        }
    }
    
    // POPULATE DIVISION DROPDOWN (A, B, C, D)
    private void populateDivisionDropdown() {
        cmbDivision.removeAllItems();
        cmbDivision.addItem("--Select Division--");
        cmbDivision.addItem("A");
        cmbDivision.addItem("B");
        cmbDivision.addItem("C");
        cmbDivision.addItem("D");
    }
    
    // POPULATE DAY DROPDOWN
    private void populateDayDropdown() {
        cmbDay.removeAllItems();
        cmbDay.addItem("-- Select Day --");
        cmbDay.addItem("Monday");
        cmbDay.addItem("Tuesday");
        cmbDay.addItem("Wednesday");
        cmbDay.addItem("Thursday");
        cmbDay.addItem("Friday");
        cmbDay.addItem("Saturday");
    }
    private void populateSubjectDropdowns(int grade) {
        try {
            con = erp.DBConnection.connect();
            
            // Get subjects for selected grade
            String query = "SELECT subject_name FROM subjects WHERE grade = ? ORDER BY subject_name";
            pst = con.prepareStatement(query);
            pst.setInt(1, grade);
            
            rs = pst.executeQuery();
            
            // Clear all period dropdowns
            cmbPeriod1.removeAllItems();
            cmbPeriod2.removeAllItems();
            cmbPeriod3.removeAllItems();
            cmbPeriod4.removeAllItems();
            cmbPeriod5.removeAllItems();
            cmbPeriod6.removeAllItems();
            
            // Add default option
            cmbPeriod1.addItem("--Select Subjects--");
            cmbPeriod2.addItem("--Select Subjects--");
            cmbPeriod3.addItem("--Select Subjects--");
            cmbPeriod4.addItem("--Select Subjects--");
            cmbPeriod5.addItem("--Select Subjects--");
            cmbPeriod6.addItem("--Select Subjects--");
            
            // Add "Free Period" option
            cmbPeriod1.addItem("Free Period");
            cmbPeriod2.addItem("Free Period");
            cmbPeriod3.addItem("Free Period");
            cmbPeriod4.addItem("Free Period");
            cmbPeriod5.addItem("Free Period");
            cmbPeriod6.addItem("Free Period");
            
            // Add subjects to all dropdowns
            while (rs.next()) {
                String subject = rs.getString("subject_name");
                if (subject != null && !subject.trim().isEmpty()) {
                    cmbPeriod1.addItem(subject);
                    cmbPeriod2.addItem(subject);
                    cmbPeriod3.addItem(subject);
                    cmbPeriod4.addItem(subject);
                    cmbPeriod5.addItem(subject);
                    cmbPeriod6.addItem(subject);
                }
            }
            
            rs.close();
            pst.close();
            con.close();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading subjects: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        selectionPanel = new javax.swing.JPanel();
        txtTitle = new javax.swing.JLabel();
        lblGrade = new javax.swing.JLabel();
        cmbGrade = new javax.swing.JComboBox<>();
        lblDivision = new javax.swing.JLabel();
        cmbDivision = new javax.swing.JComboBox<>();
        lblName = new javax.swing.JLabel();
        cmbDay = new javax.swing.JComboBox<>();
        btnLoad = new javax.swing.JButton();
        panelSchedule = new javax.swing.JPanel();
        lblScheduleTitle = new javax.swing.JLabel();
        lblInfoBanner = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        lblPeriod1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbPeriod6 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lblPeriod2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbPeriod1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        lblPeriod3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbPeriod2 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        lblPeriod4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbPeriod3 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        lblPeriod5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbPeriod4 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbPeriod5 = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setBackground(new java.awt.Color(0, 0, 102));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Manage Schedule");
        headerPanel.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 250, -1));

        backButton.setBackground(new java.awt.Color(255, 0, 0));
        backButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        backButton.setText("<-- Back To Dashboard");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        headerPanel.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, -1, -1));

        getContentPane().add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 80));

        contentPanel.setBackground(new java.awt.Color(204, 204, 204));
        contentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selectionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitle.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        txtTitle.setText("Select Class Details: ");
        selectionPanel.add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 200, 20));

        lblGrade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGrade.setText("Grade: ");
        selectionPanel.add(lblGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 45, -1, 20));

        cmbGrade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Grade--", "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6", "Grade 7", "Grade 8", "Grade 9", "Grade 10" }));
        selectionPanel.add(cmbGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        lblDivision.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDivision.setText("Division: ");
        selectionPanel.add(lblDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 45, -1, -1));

        cmbDivision.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbDivision.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Division--", "Division A", "Division B", "Division C", "Division D" }));
        selectionPanel.add(cmbDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblName.setText("Day of Week: ");
        selectionPanel.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 45, -1, -1));

        cmbDay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select Day --", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" }));
        selectionPanel.add(cmbDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        btnLoad.setBackground(new java.awt.Color(0, 204, 255));
        btnLoad.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnLoad.setText("Load Schedule");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });
        selectionPanel.add(btnLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 50, 200, 40));

        contentPanel.add(selectionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 1140, 110));

        panelSchedule.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblScheduleTitle.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        lblScheduleTitle.setText("Set Period Schedule: ");
        panelSchedule.add(lblScheduleTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, -1));

        lblInfoBanner.setBackground(new java.awt.Color(204, 255, 204));
        lblInfoBanner.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblInfoBanner.setForeground(new java.awt.Color(255, 0, 0));
        lblInfoBanner.setText("Note: Select subject for each period. Leave blank for free periods..");
        panelSchedule.add(lblInfoBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 1080, 20));

        panel1.setBackground(new java.awt.Color(204, 204, 204));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPeriod1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPeriod1.setText("Period 1:");
        panel1.add(lblPeriod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 60, -1));

        jLabel1.setText("09:00 AM - 10: 00 AM");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        panelSchedule.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 140, 40));

        cmbPeriod6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbPeriod6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Subjects--" }));
        panelSchedule.add(cmbPeriod6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 850, 28));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPeriod2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPeriod2.setText("Period 2:");
        jPanel1.add(lblPeriod2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 60, -1));

        jLabel2.setText("10:00 AM - 11:00 AM");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, -1));

        panelSchedule.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 140, 40));

        cmbPeriod1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbPeriod1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Subjects--" }));
        panelSchedule.add(cmbPeriod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 850, 28));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPeriod3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPeriod3.setText("Period 3:");
        jPanel2.add(lblPeriod3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 60, -1));

        jLabel4.setText("11:15 AM - 12:15 PM");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        panelSchedule.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 140, 40));

        cmbPeriod2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbPeriod2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Subjects--" }));
        panelSchedule.add(cmbPeriod2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 850, 28));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPeriod4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPeriod4.setText("Period 4:");
        jPanel3.add(lblPeriod4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 60, -1));

        jLabel6.setText("12:15 PM - 13:15 PM");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        panelSchedule.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 140, 40));

        cmbPeriod3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbPeriod3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Subjects--" }));
        panelSchedule.add(cmbPeriod3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 850, 28));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPeriod5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPeriod5.setText("Period 5:");
        jPanel4.add(lblPeriod5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 60, -1));

        jLabel8.setText("14:00 PM - 15:00 PM");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        panelSchedule.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 140, 40));

        cmbPeriod4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbPeriod4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Subjects--" }));
        panelSchedule.add(cmbPeriod4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 850, 28));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Period 6:");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 60, -1));

        jLabel5.setText("15:00 PM - 16:00 PM");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        panelSchedule.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 140, 40));

        cmbPeriod5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbPeriod5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Subjects--" }));
        panelSchedule.add(cmbPeriod5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 850, 28));

        btnSave.setBackground(new java.awt.Color(0, 204, 0));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save Schedule");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        panelSchedule.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 420, 150, 45));

        btnClear.setBackground(new java.awt.Color(153, 153, 153));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear All");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        panelSchedule.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 420, 150, 45));

        contentPanel.add(panelSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 1140, 480));

        getContentPane().add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1200, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
FacultyDashboard fd=new FacultyDashboard();
fd.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
String grade = (String) cmbGrade.getSelectedItem();
        String division = (String) cmbDivision.getSelectedItem();
        String day = (String) cmbDay.getSelectedItem();
        
        // Validation
        if (grade.equals("--Select Grade--") || division.equals("--Select Division--") || day.equals("-- Select Day --")) {
            JOptionPane.showMessageDialog(this, "Please select Grade, Division, and Day of Week!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Populate subject dropdowns based on grade
        populateSubjectDropdowns(Integer.parseInt(grade));
        
        try {
            con = erp.DBConnection.connect();
            
            // Check if schedule exists for this grade, division, and day
            String query = "SELECT subject, time_from, time_to FROM schedule WHERE grade = ? AND division = ? AND day_name = ? ORDER BY time_from";
            pst = con.prepareStatement(query);
            pst.setInt(1, Integer.parseInt(grade));
            pst.setString(2, division);
            pst.setString(3, day);
            
            rs = pst.executeQuery();
            
            // Store subjects in order
            String[] subjects = new String[6];
            int index = 0;
            
            while (rs.next() && index < 6) {
                String subject = rs.getString("subject");
                subjects[index] = subject != null ? subject : "--Select Subjects--";
                index++;
            }
            
            // Set subjects to period dropdowns
            if (subjects[0] != null) cmbPeriod1.setSelectedItem(subjects[0]);
            if (subjects[1] != null) cmbPeriod2.setSelectedItem(subjects[1]);
            if (subjects[2] != null) cmbPeriod3.setSelectedItem(subjects[2]);
            if (subjects[3] != null) cmbPeriod4.setSelectedItem(subjects[3]);
            if (subjects[4] != null) cmbPeriod5.setSelectedItem(subjects[4]);
            if (subjects[5] != null) cmbPeriod6.setSelectedItem(subjects[5]);
            
            if (index > 0) {
                JOptionPane.showMessageDialog(this, 
                    "✅ Schedule loaded successfully!\n\nYou can now edit and save changes.", 
                    "Schedule Loaded", 
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, 
                    "No existing schedule found for Grade " + grade + " Division " + division + " on " + day + ".\n\nYou can create a new schedule by selecting subjects and clicking 'Save Schedule'.", 
                    "New Schedule", 
                    JOptionPane.INFORMATION_MESSAGE);
            }
            
            rs.close();
            pst.close();
            con.close();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading schedule: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
String grade = (String) cmbGrade.getSelectedItem();
        String division = (String) cmbDivision.getSelectedItem();
        String day = (String) cmbDay.getSelectedItem();
        
        // Validation
        if (grade.equals("--Select Grade--") || division.equals("--Select Division--") || day.equals("-- Select Day --")) {
            JOptionPane.showMessageDialog(this, "Please select Grade, Division, and Day of Week first!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Get selected subjects
        String period1 = (String) cmbPeriod1.getSelectedItem();
        String period2 = (String) cmbPeriod2.getSelectedItem();
        String period3 = (String) cmbPeriod3.getSelectedItem();
        String period4 = (String) cmbPeriod4.getSelectedItem();
        String period5 = (String) cmbPeriod5.getSelectedItem();
        String period6 = (String) cmbPeriod6.getSelectedItem();
        
        // Convert "Free Period" to null for database
        if (period1.equals("--Select Subjects--")) period1 = null;
        else if (period1.equals("Free Period")) period1 = "Free";
        
        if (period2.equals("--Select Subjects--")) period2 = null;
        else if (period2.equals("Free Period")) period2 = "Free";
        
        if (period3.equals("--Select Subjects--")) period3 = null;
        else if (period3.equals("Free Period")) period3 = "Free";
        
        if (period4.equals("--Select Subjects--")) period4 = null;
        else if (period4.equals("Free Period")) period4 = "Free";
        
        if (period5.equals("--Select Subjects--")) period5 = null;
        else if (period5.equals("Free Period")) period5 = "Free";
        
        if (period6.equals("--Select Subjects--")) period6 = null;
        else if (period6.equals("Free Period")) period6 = "Free";
        
        // Confirmation
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Save schedule for:\n\n" +
            "Grade: " + grade + "\n" +
            "Division: " + division + "\n" +
            "Day: " + day + "\n\n" +
            "This will overwrite any existing schedule for this day.", 
            "Confirm Save", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE);
        
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        try {
            con = erp.DBConnection.connect();
            
            // Delete existing schedule for this grade, division, and day
            String deleteQuery = "DELETE FROM schedule WHERE grade = ? AND division = ? AND day_name = ?";
            PreparedStatement pstDelete = con.prepareStatement(deleteQuery);
            pstDelete.setInt(1, Integer.parseInt(grade));
            pstDelete.setString(2, division);
            pstDelete.setString(3, day);
            pstDelete.executeUpdate();
            pstDelete.close();
            
            // Time slots
            String[] timeFrom = {"09:00:00", "10:00:00", "11:15:00", "12:15:00", "14:00:00", "15:00:00"};
            String[] timeTo = {"10:00:00", "11:00:00", "12:15:00", "13:15:00", "15:00:00", "16:00:00"};
            String[] periods = {period1, period2, period3, period4, period5, period6};
            
            // Insert new schedule for all 6 periods
            String insertQuery = "INSERT INTO schedule (grade, division, day_name, subject, time_from, time_to, teacher_email) VALUES (?, ?, ?, ?, ?, ?, ?)";
            pst = con.prepareStatement(insertQuery);
            
            int savedCount = 0;
            
            for (int i = 0; i < 6; i++) {
                if (periods[i] != null) {
                    pst.setInt(1, Integer.parseInt(grade));
                    pst.setString(2, division);
                    pst.setString(3, day);
                    pst.setString(4, periods[i]);
                    pst.setString(5, timeFrom[i]);
                    pst.setString(6, timeTo[i]);
                    pst.setString(7, LoginSession.email); // Faculty email
                    
                    pst.executeUpdate();
                    savedCount++;
                }
            }
            
            pst.close();
            con.close();
            
            JOptionPane.showMessageDialog(this, 
                "✅ Schedule saved successfully!\n\n" +
                "Grade: " + grade + "\n" +
                "Division: " + division + "\n" +
                "Day: " + day + "\n" +
                "Periods Saved: " + savedCount + "/6\n" +
                "Updated by: " + LoginSession.name, 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error saving schedule: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to clear all period selections?", 
            "Clear All", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE);
        
        if (confirm == JOptionPane.YES_OPTION) {
            cmbPeriod1.setSelectedIndex(0);
            cmbPeriod2.setSelectedIndex(0);
            cmbPeriod3.setSelectedIndex(0);
            cmbPeriod4.setSelectedIndex(0);
            cmbPeriod5.setSelectedIndex(0);
            cmbPeriod6.setSelectedIndex(0);
            
            JOptionPane.showMessageDialog(this, "All periods cleared!", "Cleared", JOptionPane.INFORMATION_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FacultyManageSchedule().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbDay;
    private javax.swing.JComboBox<String> cmbDivision;
    private javax.swing.JComboBox<String> cmbGrade;
    private javax.swing.JComboBox<String> cmbPeriod1;
    private javax.swing.JComboBox<String> cmbPeriod2;
    private javax.swing.JComboBox<String> cmbPeriod3;
    private javax.swing.JComboBox<String> cmbPeriod4;
    private javax.swing.JComboBox<String> cmbPeriod5;
    private javax.swing.JComboBox<String> cmbPeriod6;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblDivision;
    private javax.swing.JLabel lblGrade;
    private javax.swing.JLabel lblInfoBanner;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPeriod1;
    private javax.swing.JLabel lblPeriod2;
    private javax.swing.JLabel lblPeriod3;
    private javax.swing.JLabel lblPeriod4;
    private javax.swing.JLabel lblPeriod5;
    private javax.swing.JLabel lblScheduleTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panelSchedule;
    private javax.swing.JPanel selectionPanel;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
