/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package erp;

/**
 *
 * @author Heet Lakhani
 */
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.Connection;

public class RegistrationForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrationForm.class.getName());

    /**
     * Creates new form RegistrationForm
     */
    public RegistrationForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        branchgroup = new javax.swing.ButtonGroup();
        divsiongroup = new javax.swing.ButtonGroup();
        btngroupGrade = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtPRN = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        rbC1 = new javax.swing.JRadioButton();
        rbB = new javax.swing.JRadioButton();
        rbC = new javax.swing.JRadioButton();
        rbD = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        rb5 = new javax.swing.JRadioButton();
        rb6 = new javax.swing.JRadioButton();
        rb7 = new javax.swing.JRadioButton();
        rb8 = new javax.swing.JRadioButton();
        rb9 = new javax.swing.JRadioButton();
        rb10 = new javax.swing.JRadioButton();
        rbA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Register Yourself");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 269, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setText("Full Name: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 117, 20));

        txtName.setToolTipText("Enter Full Name");
        txtName.setName(""); // NOI18N
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 254, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setText("Email Address: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, 20));

        txtEmail.setToolTipText("Enter Email");
        txtEmail.setName(""); // NOI18N
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 255, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setText("Password: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, 20));

        txtPassword.setToolTipText("Enter Strong Password");
        txtPassword.setName(""); // NOI18N
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 260, -1));

        jLabel5.setText("(Min 1 Uppercase 1 Lowercase 1 Number & 1 Special Character)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setText("Grade: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, 20));

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 40, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setText("Roll Number:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 130, 20));

        txtPRN.setToolTipText("Enter PRN Number");
        txtPRN.setName(""); // NOI18N
        getContentPane().add(txtPRN, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 260, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 580, 220, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel10.setText("Divison: ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, -1, 20));

        divsiongroup.add(rbC1);
        rbC1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        rbC1.setText("A");
        rbC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbC1ActionPerformed(evt);
            }
        });
        getContentPane().add(rbC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 515, -1, 20));

        divsiongroup.add(rbB);
        rbB.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        rbB.setText("B");
        getContentPane().add(rbB, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 515, -1, 20));

        divsiongroup.add(rbC);
        rbC.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        rbC.setText("C");
        getContentPane().add(rbC, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 515, -1, 20));

        divsiongroup.add(rbD);
        rbD.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        rbD.setText("D");
        rbD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDActionPerformed(evt);
            }
        });
        getContentPane().add(rbD, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, -1, -1));

        rb3.setBackground(new java.awt.Color(255, 255, 255));
        btngroupGrade.add(rb3);
        rb3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        rb3.setText("3");
        getContentPane().add(rb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 335, 50, 20));

        rb1.setBackground(new java.awt.Color(255, 255, 255));
        btngroupGrade.add(rb1);
        rb1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        rb1.setText("1");
        getContentPane().add(rb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 335, 60, 20));

        rb2.setBackground(new java.awt.Color(255, 255, 255));
        btngroupGrade.add(rb2);
        rb2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        rb2.setText("2");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });
        getContentPane().add(rb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 335, 50, 20));

        rb4.setBackground(new java.awt.Color(255, 255, 255));
        btngroupGrade.add(rb4);
        rb4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        rb4.setText("4");
        getContentPane().add(rb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 335, 50, 20));

        rb5.setBackground(new java.awt.Color(255, 255, 255));
        btngroupGrade.add(rb5);
        rb5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        rb5.setText("5");
        rb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb5ActionPerformed(evt);
            }
        });
        getContentPane().add(rb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 335, 50, 20));

        rb6.setBackground(new java.awt.Color(255, 255, 255));
        btngroupGrade.add(rb6);
        rb6.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        rb6.setText("6");
        getContentPane().add(rb6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 375, 60, 20));

        rb7.setBackground(new java.awt.Color(255, 255, 255));
        btngroupGrade.add(rb7);
        rb7.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        rb7.setText("7");
        getContentPane().add(rb7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 375, 50, 20));

        rb8.setBackground(new java.awt.Color(255, 255, 255));
        btngroupGrade.add(rb8);
        rb8.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        rb8.setText("8");
        getContentPane().add(rb8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 375, 50, 20));

        rb9.setBackground(new java.awt.Color(255, 255, 255));
        btngroupGrade.add(rb9);
        rb9.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        rb9.setText("9");
        getContentPane().add(rb9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 375, 50, 20));

        btngroupGrade.add(rb10);
        rb10.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        rb10.setText("10");
        getContentPane().add(rb10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 50, -1));

        rbA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/erp/RegistrationImage (1).jpg"))); // NOI18N
        getContentPane().add(rbA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String name = txtName.getText().trim();
String email = txtEmail.getText().trim();
String password = txtPassword.getText().trim();
String prn = txtPRN.getText().trim();

// ------------------ BASIC VALIDATIONS ------------------
if(name.isEmpty() || email.isEmpty() || password.isEmpty())
{
    JOptionPane.showMessageDialog(this, "Enter All Fields");
    return;
}

if(!email.matches("[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$"))
{
    JOptionPane.showMessageDialog(this, "Enter a Valid E-mail Address");
    return;
}

if(!email.endsWith("@college.in"))
{
    JOptionPane.showMessageDialog(this, "E-mail should end with @college.in");
    return;
}

// PASSWORD VALIDATION
String passwordPattern = 
    "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!#%*?&])[A-Za-z\\d@$!#%*?&]{8,}$";

if(!password.matches(passwordPattern))
{
    JOptionPane.showMessageDialog(this,
        "Password should contain:\n1. Uppercase\n2. Lowercase\n3. Number\n4. Special Character");
    return;
}

// ------------------ ROLE DETECTION ------------------
String role = email.contains("08@") ? "Student" : "Faculty";

int roll = -1;

// ------------------ ROLL NUMBER ONLY FOR STUDENTS ------------------
if(role.equals("Student"))
{
    if(prn.isEmpty())
    {
        JOptionPane.showMessageDialog(this, "Enter Roll Number");
        return;
    }

    if(!prn.matches("\\d{2}"))
    {
        JOptionPane.showMessageDialog(this, "Enter Valid 2-Digit Number");
        return;
    }

    roll = Integer.parseInt(prn);
}
else
{
   if(prn.matches("\\d{2}"))
    {
        roll = Integer.parseInt(prn);
    }
}

// ------------------ GRADE SELECTION ------------------
String grade = null;
if(rb1.isSelected()) grade = "1";
else if(rb2.isSelected()) grade = "2";
else if(rb3.isSelected()) grade = "3";
else if(rb4.isSelected()) grade = "4";
else if(rb5.isSelected()) grade = "5";
else if(rb6.isSelected()) grade = "6";
else if(rb7.isSelected()) grade = "7";
else if(rb8.isSelected()) grade = "8";
else if(rb9.isSelected()) grade = "9";
else if(rb10.isSelected()) grade = "10";
if(role.equals("Student")&& grade==null)
{
    JOptionPane.showMessageDialog(this,"Select Grade");
    return;
}
// ------------------ DIVISION SELECTION (A/B/C/D) ------------------
String division = null;
if(role.equals("Student"))
{
    if(rbC1.isSelected()) division = "A";
    else if(rbB.isSelected()) division = "B";
    else if(rbC.isSelected()) division = "C";
    else if(rbD.isSelected()) division = "D";
    if(division == null) {
        JOptionPane.showMessageDialog(this, "Select Division");
        return;
    }
}

// ------------------ DATABASE INSERT ------------------
try 
{
    Connection con = DBConnection.connect();
    
    String sql = "INSERT INTO users(name, email, password, role, grade, division, roll_no) "
               + "VALUES(?,?,?,?,?,?,?)";

    PreparedStatement pst = con.prepareStatement(sql);
    pst.setString(1, name);
    pst.setString(2, email);
    pst.setString(3, password);
    pst.setString(4, role);
    pst.setString(5, grade);

    if(division == null)
        pst.setNull(6, java.sql.Types.VARCHAR);
    else
        pst.setString(6, division);

    if(roll == -1)
        pst.setNull(7, java.sql.Types.INTEGER);
    else
        pst.setInt(7, roll);

    pst.executeUpdate();

    JOptionPane.showMessageDialog(this, "Registration Successful!");

    LoginForm login = new LoginForm();
    login.setVisible(true);
    this.dispose();
}
catch(Exception e)
{
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rbC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbC1ActionPerformed

    private void rbDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb2ActionPerformed

    private void rb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistrationForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup branchgroup;
    private javax.swing.ButtonGroup btngroupGrade;
    private javax.swing.ButtonGroup divsiongroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb10;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JRadioButton rb6;
    private javax.swing.JRadioButton rb7;
    private javax.swing.JRadioButton rb8;
    private javax.swing.JRadioButton rb9;
    private javax.swing.JLabel rbA;
    private javax.swing.JRadioButton rbB;
    private javax.swing.JRadioButton rbC;
    private javax.swing.JRadioButton rbC1;
    private javax.swing.JRadioButton rbD;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPRN;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
