/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package erp;

/**
 *
 * @author Heet Lakhani
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class StudentDashboard extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentDashboard.class.getName());
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    /**
     * Creates new form StudentDashboard
     */
    public StudentDashboard() {
        initComponents();
        setLocationRelativeTo(null);
        // SET STUDENT NAME
        lblWelcome.setText("Welcome " + LoginSession.name);
        lblStudentName.setText(LoginSession.name);
        loadTodaysSchedule();
        loadLatestNotices();
    }

    private void loadTodaysSchedule() {
        try {
            con = erp.DBConnection.connect();

            // Get today's day of week
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("EEEE");
            String today = sdf.format(new java.util.Date());

            String query = "SELECT subject, time_from, time_to FROM schedule WHERE grade = ? AND division = ? AND day_name = ? ORDER BY time_from";
            pst = con.prepareStatement(query);
            pst.setInt(1, LoginSession.grade);
            pst.setString(2, LoginSession.division);
            pst.setString(3, today);

            rs = pst.executeQuery();

            StringBuilder schedule = new StringBuilder();
            schedule.append("<html><b>Today's Schedule (").append(today).append("):</b><br><br>");

            boolean hasSchedule = false;
            while (rs.next()) {
                hasSchedule = true;
                String subject = rs.getString("subject");
                String timeFrom = rs.getString("time_from");
                String timeTo = rs.getString("time_to");

                // Format time
                String formattedFrom = formatTime(timeFrom);
                String formattedTo = formatTime(timeTo);

                schedule.append("• ").append(subject)
                        .append(" (").append(formattedFrom).append(" - ").append(formattedTo).append(")<br>");
            }

            if (!hasSchedule) {
                schedule.append("No classes scheduled for today.");
            }

            schedule.append("</html>");
            jLabel6.setText(schedule.toString());

            rs.close();
            pst.close();
            con.close();

        } catch (Exception e) {
            jLabel6.setText("<html>Error loading schedule</html>");
            e.printStackTrace();
        }
    }

    private String formatTime(String time) {
        try {
            java.text.SimpleDateFormat input = new java.text.SimpleDateFormat("HH:mm:ss");
            java.text.SimpleDateFormat output = new java.text.SimpleDateFormat("hh:mm a");
            return output.format(input.parse(time));
        } catch (Exception e) {
            return time;
        }
    }

    private void loadLatestNotices() {
    try {
        con = erp.DBConnection.connect();

        String query = "SELECT title, message, date FROM notices ORDER BY date DESC LIMIT 5";
        pst = con.prepareStatement(query);
        rs = pst.executeQuery();

        StringBuilder notices = new StringBuilder();
        notices.append("<html>");
        notices.append("<b>Latest Notices:</b><br><br>");

        boolean hasNotices = false;

        while (rs.next()) {
            hasNotices = true;

            String title = rs.getString("title");
            String message = rs.getString("message");

            // Optional: limit message length for UI safety
            if (message.length() > 100) {
                message = message.substring(0, 100) + "...";
            }

            notices.append("&#8226; "); // bullet
            notices.append("<b>").append(title).append(":</b> ");
            notices.append(message);
            notices.append("<br><br>");
        }

        if (!hasNotices) {
            notices.append("No notices available.");
        }

        notices.append("</html>");
        jLabel7.setText(notices.toString());

        rs.close();
        pst.close();
        con.close();

    } catch (Exception e) {
        jLabel7.setText("<html>Error loading notices</html>");
        e.printStackTrace();
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblStudentName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnAttendance = new javax.swing.JButton();
        btnMarks = new javax.swing.JButton();
        btnSchedule = new javax.swing.JButton();
        btnNotices = new javax.swing.JButton();
        sidebarPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelSchedule = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        panelNotices = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Student DashBoard");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 230, -1));

        lblStudentName.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblStudentName.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentName.setText("Student Name");
        getContentPane().add(lblStudentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 15, 120, -1));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LogOut");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, 110, 35));

        btnHome.setBackground(new java.awt.Color(153, 153, 255));
        btnHome.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 230, 70));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 70));

        btnAttendance.setBackground(new java.awt.Color(153, 153, 255));
        btnAttendance.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        btnAttendance.setText("Attendance");
        btnAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttendanceActionPerformed(evt);
            }
        });
        getContentPane().add(btnAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 225, 230, 70));

        btnMarks.setBackground(new java.awt.Color(153, 153, 255));
        btnMarks.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        btnMarks.setText("Marks");
        btnMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarksActionPerformed(evt);
            }
        });
        getContentPane().add(btnMarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 230, 70));

        btnSchedule.setBackground(new java.awt.Color(153, 153, 255));
        btnSchedule.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        btnSchedule.setText("Schedule");
        getContentPane().add(btnSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 475, 230, 70));

        btnNotices.setBackground(new java.awt.Color(153, 153, 255));
        btnNotices.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        btnNotices.setText("Notices");
        getContentPane().add(btnNotices, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 230, 70));

        sidebarPanel.setBackground(new java.awt.Color(0, 0, 0));
        sidebarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(sidebarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 250, 630));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(0, 0, 204));
        lblWelcome.setText("Welcome, Student!");
        lblWelcome.setMaximumSize(new java.awt.Dimension(30, 30));
        lblWelcome.setMinimumSize(new java.awt.Dimension(30, 30));
        lblWelcome.setPreferredSize(new java.awt.Dimension(30, 30));
        mainPanel.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 360, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Here's your dashboard overview");
        mainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        panelSchedule.setBackground(new java.awt.Color(204, 204, 204));
        panelSchedule.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel6.setText("Today's Schedule:");
        panelSchedule.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelSchedule.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 10, 440));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelSchedule.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 390, 10));

        mainPanel.add(panelSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 400, 440));

        panelNotices.setBackground(new java.awt.Color(204, 204, 204));
        panelNotices.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel7.setText("Latest Notice: ");
        panelNotices.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelNotices.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 10, 440));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelNotices.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 440, 10));

        mainPanel.add(panelNotices, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 450, 440));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        mainPanel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 10));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        mainPanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 10, 620));

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        mainPanel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 940, 10));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 950, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttendanceActionPerformed
        StudentAttendancePage sap = new StudentAttendancePage();
        sap.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnAttendanceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarksActionPerformed
        StudentMarksPage smp = new StudentMarksPage();
        smp.setVisible(true);
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_btnMarksActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
StudentDashboard sd=new StudentDashboard();
sd.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttendance;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnMarks;
    private javax.swing.JButton btnNotices;
    private javax.swing.JButton btnSchedule;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelNotices;
    private javax.swing.JPanel panelSchedule;
    private javax.swing.JPanel sidebarPanel;
    // End of variables declaration//GEN-END:variables
}
